import { ProductModel } from "./../models/ProductModel";

export const productData: ProductModel[] = [
  {
    id: 0,
    seen: 985,
    city: "Ташкент",
    address: "Ташкент, Яккасарай, ул Шотаруставели, 12В",
    date: "2022-04-21T12:31",
    title: "Срочно Продается 4 ком квартира 170 кв.м дом Нова Стройка",
    image_url: "/images/products/product_0/0.jpeg",
    images: [
      "/images/products/product_0/0.jpeg",
      "/images/products/product_0/1.jpeg",
      "/images/products/product_0/2.jpeg",
      "/images/products/product_0/3.jpeg",
      "/images/products/product_0/4.jpeg",
    ],
    amount: 1,
    has_guarantee: true,
    is_sale: true,
    sale_time: "12",
    price: 200000,
    old_price: 220000,
    is_favorite: false,
    currency: "usd",
    info: {
      category: "Квартиры",
      condition: 10,
      manufacturer: "Orient House",
      model: "Евро дом",
      color: "-",
      storage: 0,
      description:
        "Сдаётся свежая квартира с новым ремонтом в удобном расположении для подробной информации звоните ! С предоплатой 800$",
    },
  },
  {
    id: 1,
    seen: 1290,
    city: "Ташкент",
    address: "Ташкент, Яшнабад, ул Ош, 92",
    date: "2022-04-18T10:31",
    title: "Витринный Морозильник PREMIER PRM-346",
    image_url: "/images/products/product_1/0.jpeg",
    images: [
      "/images/products/product_1/0.jpeg",
      "/images/products/product_1/1.jpeg",
      "/images/products/product_1/2.jpeg",
    ],
    amount: 1,
    has_guarantee: true,
    sale_time: "12",
    price: 200000,
    is_favorite: false,
    currency: "uzs",
    info: {
      category: "Бытовая техника",
      condition: 9,
      manufacturer: "PREMIER",
      model: "PRM-346",
      color: "Белый",
      storage: 0,
      description:
        "Морозильник PREMIER PRM-346. (254литровый). С завода MIDEA. Гарантия 3года. Бесплатная доставка по Ташкенту.",
    },
  },
  {
    id: 2,
    seen: 390,
    city: "Ташкент",
    address: "Ташкент, Яшнабад, ул Ош, 92",
    date: "2022-04-23T22:31",
    title: "Мерседес S320 W220",
    image_url: "/images/products/product_2/0.jpeg",
    images: [
      "/images/products/product_2/0.jpeg",
      "/images/products/product_2/1.jpeg",
      "/images/products/product_2/2.jpeg",
    ],
    amount: 1,
    has_guarantee: true,
    sale_time: "23",
    price: 129917900,
    is_favorite: false,
    currency: "uzs",
    info: {
      category: "Транспорт",
      condition: 8,
      manufacturer: "Mercedes-Benz",
      model: "S320 W220",
      color: "Вишнёвый",
      storage: 0,
      description:
        "Продажа. Возможен обмен, предлагайте варианты. Подробности по машине по телефону или при встрече",
    },
  },
  {
    id: 3,
    seen: 1200,
    city: "Ташкент",
    address: "Ташкент, Яккасарай, Гостиница Гранд-мир",
    date: "2022-04-19T13:31",
    title: "LED Ekran LED экраны Продажа Прокат",
    image_url: "/images/products/product_3/0.jpeg",
    images: [
      "/images/products/product_3/0.jpeg",
      "/images/products/product_3/1.jpeg",
      "/images/products/product_3/2.jpeg",
      "/images/products/product_3/3.jpeg",
    ],
    amount: 400,
    has_guarantee: true,
    is_sale: true,
    sale_time: "43",
    price: 54,
    old_price: 68,
    is_favorite: false,
    currency: "usd",
    info: {
      category: "Бизнес и услуги",
      condition: 10,
      manufacturer: "Ekran LED",
      model: "Р8 Р6 Р10",
      color: "Палитра",
      storage: 0,
      description:
        "Наружный Р8 Р6 Р10\nВнутренний Р3 Р4 Р5\n\nНаша компания “PRO LED” на протяжении нескольких лет лидирует в сфере изготовления, монтажа и настройки своей продукции, оправдывая доверие своих партнеров. Предлагаем Вам свои продукции и выражаем уверенность в плодотворном и взаимовыгодном сотрудничестве. В нашем предприятии производятся высококачественные светодиодные информационные табло, (LED) экраны\n\nПОЧЕМУ МЫ ЛУЧШЕ?\n\n«PRO LED» работает по всей территории Республики Узбекистан, берём заказы любой сложности, размера.\n\nНЕОГРАНИЧЕННЫЕ ВОЗМОЖНОСТИ\nГарантия\nДлительный срок службы\nОфициальный дилер\nНизкие цены\nВозможность использования в любом закрытом пространстве\n\nНАДЁЖНОСТЬ\nПылезащита и влагозащита\nЗащита от механических повреждений\nУстойчивость к перепадам температуры\nБезотказность в работе как в сильную жару, так и в мороз\n\nКАЧЕСТВО ИЗОБРАЖЕНИЯ\nВысокое качество\nШирокий угол обзора\nЯркость и высокое разрешение\nПревосходное качество изображения даже под прямыми солнечными лучами\n\nЭКОНОМИЧНОСТЬ\nСветодиодная техника потребляет минимум электроэнергии\nИдеальная цветовая палитра\nВозможность выбрать подходящий размер экрана – разнообразие выбора моделей\nДостаточно длительный срок эксплуатации",
    },
  },
  {
    id: 4,
    seen: 9732,
    city: "Ташкент",
    address: "Ташкент, Юнусабад, рынок Малика",
    date: "2022-04-10T20:54",
    title: "Macbook Air 13” m1 8/256gb 2020г",
    image_url: "/images/products/product_4/0.jpeg",
    images: [
      "/images/products/product_4/0.jpeg",
      "/images/products/product_4/1.jpeg",
      "/images/products/product_4/2.jpeg",
      "/images/products/product_4/3.jpeg",
      "/images/products/product_4/4.jpeg",
    ],
    amount: 20,
    has_guarantee: true,
    is_sale: false,
    sale_time: "43",
    price: 10280452,
    // old_price: 68,
    is_favorite: false,
    currency: "uzs",
    info: {
      category: "Ноутбуки",
      condition: 10,
      manufacturer: "Apple",
      model: "Macbook air 13",
      color: "Темный",
      storage: 256,
      description:
        "Как новый !!!\n\n\nСостояние: идеальное как новое\nРаботоспособность: отличное без дефектов\nКомплект: полный\nЦикл заряда: 20 раз\n\nРемонт: не вскрывался и не ремонтирован\n\n\nГарантия: неделя",
    },
  },
  {
    id: 5,
    seen: 1340,
    city: "Ташкент",
    address: "Ташкент, Яшнабад, 12А",
    date: "2022-04-08T12:39",
    title: "Продается шотландские шиншилла",
    image_url: "/images/products/product_5/0.jpeg",
    images: [
      "/images/products/product_5/0.jpeg",
      "/images/products/product_5/1.jpeg",
    ],
    amount: 1,
    has_guarantee: true,
    is_sale: false,
    sale_time: "43",
    price: 2485384,
    // old_price: 68,
    is_favorite: true,
    currency: "uzs",
    info: {
      category: "Животные",
      condition: 10,
      manufacturer: "Шотландия",
      model: "Шиншилла",
      color: "Белый",
      storage: 0,
      description:
        "Готовиться продаже чисто кровный шотландский короткошёрстные серебристый шиншилла папа серебристый шиншилла мама золотистый шиншилла родились 17 февраля тел +998974007184",
    },
  },
  {
    id: 6,
    seen: 4520,
    city: "Ташкент",
    address: "Ташкент, Юнусабад, 5квр.",
    date: "2022-04-07T04:21",
    title: "Игровое кресло - Cougar ARMOR Black",
    image_url: "/images/products/product_6/0.jpeg",
    images: [
      "/images/products/product_6/0.jpeg",
      "/images/products/product_6/1.jpeg",
      "/images/products/product_6/2.jpeg",
    ],
    amount: 23,
    has_guarantee: true,
    is_sale: true,
    sale_time: "24",
    price: 334,
    old_price: 400,
    is_favorite: false,
    currency: "usd",
    info: {
      category: "Офисная мебель",
      condition: 10,
      manufacturer: "Cougar",
      model: "ARMOR",
      color: "Черный",
      storage: 0,
      description:
        "+ компьютерное кресло до 120 кг\n+ с подголовником, с подлокотниками\n\n+ материал крестовины: металл\n\nрегулировка высоты сиденья: «газлифт»\n+ особенности: механизм качания, поясничный упор\n\nНе является публичной офертой, цены уточняйте у консультанта! Из-за нестабильности рынка цены меняются",
    },
  },
  {
    id: 7,
    seen: 3302,
    city: "Ташкент",
    address: "Ташкент, Юнусабад, Рынок Малика",
    date: "2022-04-05T20:21",
    title: "телевизор Samsung Smart 43/Android 4К. Бесплатная доставка",
    image_url: "/images/products/product_7/0.jpeg",
    images: [
      "/images/products/product_7/0.jpeg",
      "/images/products/product_7/1.jpeg",
      "/images/products/product_7/2.jpeg",
    ],
    amount: 10,
    has_guarantee: true,
    is_sale: false,
    sale_time: "24",
    price: 2880786,
    // old_price: 400,
    is_favorite: false,
    currency: "uzs",
    info: {
      category: "Телевизоры",
      condition: 7,
      manufacturer: "Samsung",
      model: "Smart 43",
      color: "Черный",
      storage: 8,
      description:
        "Телевизор Samsung Smart 43 с оптового склада в Ташкенте. Бесплатная доставка по городу. Матрица IPS под защитой. Встроенная память 8ГБ оперативная 1,5ГБ. Операционная система Android 9. Бесплатная прошивка установка более 1500 бесплатных каналов более 300000 фильмов youtube без рекламы. Гарантия 1 год. Один месяц полная замена. * ТВ на Android 9, доступны миллионы приложений.",
    },
  },
  {
    id: 8,
    seen: 985,
    city: "Ташкент",
    address: "Ташкент, Яккасарай, ул Шотаруставели, 12В",
    date: "2022-04-21T12:31",
    title: "Срочно Продается 4 ком квартира 170 кв.м дом Нова Стройка",
    image_url: "/images/products/product_0/0.jpeg",
    images: [
      "/images/products/product_0/0.jpeg",
      "/images/products/product_0/1.jpeg",
      "/images/products/product_0/2.jpeg",
      "/images/products/product_0/3.jpeg",
      "/images/products/product_0/4.jpeg",
    ],
    amount: 1,
    has_guarantee: true,
    is_sale: true,
    sale_time: "12",
    price: 200000,
    old_price: 220000,
    is_favorite: false,
    currency: "usd",
    info: {
      category: "Квартиры",
      condition: 10,
      manufacturer: "Orient House",
      model: "Евро дом",
      color: "-",
      storage: 0,
      description:
        "Сдаётся свежая квартира с новым ремонтом в удобном расположении для подробной информации звоните ! С предоплатой 800$",
    },
  },
  {
    id: 9,
    seen: 1290,
    city: "Ташкент",
    address: "Ташкент, Яшнабад, ул Ош, 92",
    date: "2022-04-18T10:31",
    title: "Витринный Морозильник PREMIER PRM-346",
    image_url: "/images/products/product_1/0.jpeg",
    images: [
      "/images/products/product_1/0.jpeg",
      "/images/products/product_1/1.jpeg",
      "/images/products/product_1/2.jpeg",
    ],
    amount: 1,
    has_guarantee: true,
    sale_time: "12",
    price: 200000,
    is_favorite: false,
    currency: "uzs",
    info: {
      category: "Бытовая техника",
      condition: 9,
      manufacturer: "PREMIER",
      model: "PRM-346",
      color: "Белый",
      storage: 0,
      description:
        "Морозильник PREMIER PRM-346. (254литровый). С завода MIDEA. Гарантия 3года. Бесплатная доставка по Ташкенту.",
    },
  },
  {
    id: 10,
    seen: 390,
    city: "Ташкент",
    address: "Ташкент, Яшнабад, ул Ош, 92",
    date: "2022-04-23T22:31",
    title: "Мерседес S320 W220",
    image_url: "/images/products/product_2/0.jpeg",
    images: [
      "/images/products/product_2/0.jpeg",
      "/images/products/product_2/1.jpeg",
      "/images/products/product_2/2.jpeg",
    ],
    amount: 1,
    has_guarantee: true,
    sale_time: "23",
    price: 129917900,
    is_favorite: false,
    currency: "uzs",
    info: {
      category: "Транспорт",
      condition: 8,
      manufacturer: "Mercedes-Benz",
      model: "S320 W220",
      color: "Вишнёвый",
      storage: 0,
      description:
        "Продажа. Возможен обмен, предлагайте варианты. Подробности по машине по телефону или при встрече",
    },
  },
  {
    id: 11,
    seen: 1200,
    city: "Ташкент",
    address: "Ташкент, Яккасарай, Гостиница Гранд-мир",
    date: "2022-04-19T13:31",
    title: "LED Ekran LED экраны Продажа Прокат",
    image_url: "/images/products/product_3/0.jpeg",
    images: [
      "/images/products/product_3/0.jpeg",
      "/images/products/product_3/1.jpeg",
      "/images/products/product_3/2.jpeg",
      "/images/products/product_3/3.jpeg",
    ],
    amount: 400,
    has_guarantee: true,
    is_sale: true,
    sale_time: "43",
    price: 54,
    old_price: 68,
    is_favorite: false,
    currency: "usd",
    info: {
      category: "Бизнес и услуги",
      condition: 10,
      manufacturer: "Ekran LED",
      model: "Р8 Р6 Р10",
      color: "Палитра",
      storage: 0,
      description:
        "Наружный Р8 Р6 Р10\nВнутренний Р3 Р4 Р5\n\nНаша компания “PRO LED” на протяжении нескольких лет лидирует в сфере изготовления, монтажа и настройки своей продукции, оправдывая доверие своих партнеров. Предлагаем Вам свои продукции и выражаем уверенность в плодотворном и взаимовыгодном сотрудничестве. В нашем предприятии производятся высококачественные светодиодные информационные табло, (LED) экраны\n\nПОЧЕМУ МЫ ЛУЧШЕ?\n\n«PRO LED» работает по всей территории Республики Узбекистан, берём заказы любой сложности, размера.\n\nНЕОГРАНИЧЕННЫЕ ВОЗМОЖНОСТИ\nГарантия\nДлительный срок службы\nОфициальный дилер\nНизкие цены\nВозможность использования в любом закрытом пространстве\n\nНАДЁЖНОСТЬ\nПылезащита и влагозащита\nЗащита от механических повреждений\nУстойчивость к перепадам температуры\nБезотказность в работе как в сильную жару, так и в мороз\n\nКАЧЕСТВО ИЗОБРАЖЕНИЯ\nВысокое качество\nШирокий угол обзора\nЯркость и высокое разрешение\nПревосходное качество изображения даже под прямыми солнечными лучами\n\nЭКОНОМИЧНОСТЬ\nСветодиодная техника потребляет минимум электроэнергии\nИдеальная цветовая палитра\nВозможность выбрать подходящий размер экрана – разнообразие выбора моделей\nДостаточно длительный срок эксплуатации",
    },
  },
  {
    id: 12,
    seen: 9732,
    city: "Ташкент",
    address: "Ташкент, Юнусабад, рынок Малика",
    date: "2022-04-10T20:54",
    title: "Macbook Air 13” m1 8/256gb 2020г",
    image_url: "/images/products/product_4/0.jpeg",
    images: [
      "/images/products/product_4/0.jpeg",
      "/images/products/product_4/1.jpeg",
      "/images/products/product_4/2.jpeg",
      "/images/products/product_4/3.jpeg",
      "/images/products/product_4/4.jpeg",
    ],
    amount: 20,
    has_guarantee: true,
    is_sale: false,
    sale_time: "43",
    price: 10280452,
    // old_price: 68,
    is_favorite: false,
    currency: "uzs",
    info: {
      category: "Ноутбуки",
      condition: 10,
      manufacturer: "Apple",
      model: "Macbook air 13",
      color: "Темный",
      storage: 256,
      description:
        "Как новый !!!\n\n\nСостояние: идеальное как новое\nРаботоспособность: отличное без дефектов\nКомплект: полный\nЦикл заряда: 20 раз\n\nРемонт: не вскрывался и не ремонтирован\n\n\nГарантия: неделя",
    },
  },
  {
    id: 13,
    seen: 1340,
    city: "Ташкент",
    address: "Ташкент, Яшнабад, 12А",
    date: "2022-04-08T12:39",
    title: "Продается шотландские шиншилла",
    image_url: "/images/products/product_5/0.jpeg",
    images: [
      "/images/products/product_5/0.jpeg",
      "/images/products/product_5/1.jpeg",
    ],
    amount: 1,
    has_guarantee: true,
    is_sale: false,
    sale_time: "43",
    price: 2485384,
    // old_price: 68,
    is_favorite: true,
    currency: "uzs",
    info: {
      category: "Животные",
      condition: 10,
      manufacturer: "Шотландия",
      model: "Шиншилла",
      color: "Белый",
      storage: 0,
      description:
        "Готовиться продаже чисто кровный шотландский короткошёрстные серебристый шиншилла папа серебристый шиншилла мама золотистый шиншилла родились 17 февраля тел +998974007184",
    },
  },
  {
    id: 14,
    seen: 4520,
    city: "Ташкент",
    address: "Ташкент, Юнусабад, 5квр.",
    date: "2022-04-07T04:21",
    title: "Игровое кресло - Cougar ARMOR Black",
    image_url: "/images/products/product_6/0.jpeg",
    images: [
      "/images/products/product_6/0.jpeg",
      "/images/products/product_6/1.jpeg",
      "/images/products/product_6/2.jpeg",
    ],
    amount: 23,
    has_guarantee: true,
    is_sale: true,
    sale_time: "24",
    price: 334,
    old_price: 400,
    is_favorite: false,
    currency: "usd",
    info: {
      category: "Офисная мебель",
      condition: 10,
      manufacturer: "Cougar",
      model: "ARMOR",
      color: "Черный",
      storage: 0,
      description:
        "+ компьютерное кресло до 120 кг\n+ с подголовником, с подлокотниками\n\n+ материал крестовины: металл\n\nрегулировка высоты сиденья: «газлифт»\n+ особенности: механизм качания, поясничный упор\n\nНе является публичной офертой, цены уточняйте у консультанта! Из-за нестабильности рынка цены меняются",
    },
  },
  {
    id: 15,
    seen: 3302,
    city: "Ташкент",
    address: "Ташкент, Юнусабад, Рынок Малика",
    date: "2022-04-05T20:21",
    title: "телевизор Samsung Smart 43/Android 4К. Бесплатная доставка",
    image_url: "/images/products/product_7/0.jpeg",
    images: [
      "/images/products/product_7/0.jpeg",
      "/images/products/product_7/1.jpeg",
      "/images/products/product_7/2.jpeg",
    ],
    amount: 10,
    has_guarantee: true,
    is_sale: false,
    sale_time: "24",
    price: 2880786,
    // old_price: 400,
    is_favorite: false,
    currency: "uzs",
    info: {
      category: "Телевизоры",
      condition: 7,
      manufacturer: "Samsung",
      model: "Smart 43",
      color: "Черный",
      storage: 8,
      description:
        "Телевизор Samsung Smart 43 с оптового склада в Ташкенте. Бесплатная доставка по городу. Матрица IPS под защитой. Встроенная память 8ГБ оперативная 1,5ГБ. Операционная система Android 9. Бесплатная прошивка установка более 1500 бесплатных каналов более 300000 фильмов youtube без рекламы. Гарантия 1 год. Один месяц полная замена. * ТВ на Android 9, доступны миллионы приложений.",
    },
  },
];

export const productAmountsPrice = [
  {
    id: 0,
    name_ru: "1 товар - бесплатно",
    name_uz: "1 та махсулот - бепул",
    name_oz: "1 ta mahsulot - bepul",
  },
  {
    id: 1,
    name_ru: "2 товара - 500 сум",
    name_uz: "2 та махсулот - 500 сум",
    name_oz: "2 ta mahsulot - 500 so'm",
  },
  {
    id: 2,
    name_ru: "3 товара - 1000 сум",
    name_uz: "3 та махсулот - 1000 сум",
    name_oz: "3 ta mahsulot - 1000 so'm",
  },
  {
    id: 3,
    name_ru: "4 товара - 2000 сум",
    name_uz: "4 та махсулот - 2000 сум",
    name_oz: "4 ta mahsulot - 2000 so'm",
  },
  {
    id: 4,
    name_ru: "5 товаров - 3500 сум",
    name_uz: "5 та махсулот - 3500 сум",
    name_oz: "5 ta mahsulot - 3500 so'm",
  },
];
